app: kill8s
port: 8888
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password:
  database: test
  charset: utf8mb4
  prefix: ""
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: false
  log_zap: false
#redis:
#  host: 127.0.0.1
#  port: 6379
#  password: 123456
#  db: 0
#  pool_size: 100
#  idle_timeout: 300
#  max_idle_timeout: 300
#  max_active_timeout: 300
k8s:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5akNDQWJLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJd01EWXhOakEzTURFeU5Wb1lEekl4TWpBd05USXpNRGN3TVRJMVdqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnRLSy9DT0RlTnc0RmhnenVZUHZyN1ZGN080ZVVnSkE5WEkvUGR0eCtqbEcrYmE1Qy96OVBlelZ6b3d3VVZpaUMKT01xT2ZkQ0U4Y1Q5YUk0TGxhM0hlNmtCczR2cld4L2t1eS9iZklYWkZBWXp5cUxJNVY0WG1LZEQ1dVBGQU9iVgo2OEtqTENTUytsVTJvbkZVZmxObDFhQVlhSE1IZkNvSWU1SEY2UmpYSjI3b2pyRFVsbWljZUFHVE05UEZMTHhXCjZ4N0hZNXVNeXhjMSt5QVdUOUhMeko0di9HWHRzdnZKbEJHTWh5SkVuL1Q2STRiRUNhN0JzZnY4c0MwbmlYL3EKejgwS2pOTjROYk1qdFpGYVIzT0xKRGRrWFF4MWt0RzUwUWFBb00yL1VPVndzRUx4OGFndHp6ZkpDcUxralpDRwpDNHZvUnZBQ2pscnNDWnpuTkVRZnF3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFiOHg5L0JVd2N6YU9kNWNHUFZLSXdwdEUKd0FaelFFVmN0OUxIUXFNODZTRy9zYUJBZHQ2STZ6SE9XVXhKbjBQbTR4OWhMMW8yL2NOQmJkTlhNR0hhbFgxTwprZm03eG9Kb0J5aEp2c0tpeWUxelQwaWUwNnZRNllUSHNLS1dMU3B1a2hvdnZURzFpOHB6NUZxMk9VYlJrMWw1Cmc0Q2FqR0cvdU02YlZQa2ZnTGFubmJHcXU2eVpzMDAwdktrNFFpMXgyNmVJZTh3bU8xUHU5KzFTWll5YkpvMFQKaEVLRnRiMFhJTXNDY0hPK1pLN1BpTUFKMnN4WDZRcm5vRkRMNFdvamNiR1ZFMG04dFNvNlVNSHRSbG1xRGREawpBd2xIdXBZUE11dWcvZm9VU3lUUjI3Q2R4NkJiSEQ0M0NBQzBBWkpZSGoxVElDc0RVcm1ORllPYkt0VlJnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://10.159.1.71:6443
      name: https://10.159.1.71:6443
    - cluster:
        certificate-authority: /Users/mulinbiao/.minikube/ca.crt
        extensions:
        - extension:
            last-update: Fri, 08 Sep 2023 11:19:30 CST
            provider: minikube.sigs.k8s.io
            version: v1.30.1
          name: cluster_info
        server: https://127.0.0.1:64836
      name: minikube
    contexts:
    - context:
        cluster: minikube
        extensions:
        - extension:
            last-update: Fri, 08 Sep 2023 11:19:30 CST
            provider: minikube.sigs.k8s.io
            version: v1.30.1
          name: context_info
        namespace: default
        user: minikube
      name: minikube
    - context:
        cluster: https://10.159.1.71:6443
        user: tidb-kube
      name: registry
    current-context: minikube
    kind: Config
    preferences: {}
    users:
    - name: minikube
      user:
        client-certificate: /Users/mulinbiao/.minikube/profiles/minikube/client.crt
        client-key: /Users/mulinbiao/.minikube/profiles/minikube/client.key
    - name: tidb-kube
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaekNDQWsrZ0F3SUJBZ0lVZTZvQ1hrZmZMOUhSdFEvblZ0VnkwRll0RWlBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekFnRncweU1qQTVNVGN3TkRFMk1EQmFHQTh5TVRJeApNRGd5TkRBME1UWXdNRm93WkRFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBZ1RCMEpsYVdwcGJtY3hFREFPCkJnTlZCQWNUQjBKbGFVcHBibWN4RERBS0JnTlZCQW9UQTJzNGN6RVBNQTBHQTFVRUN4TUdVM2x6ZEdWdE1SSXcKRUFZRFZRUURFd2wwYVdSaUxXdDFZbVV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQgpBUUM2clBMdmxoUnBCczF4SkY5bW1RbXN0L25SNENrYnVpaVhTUFlPbTlOeFpqK3JyaG9EdmNhenlTS2RlTkM5CmZ1Sk1HMzdRcFNEeDdTaVB1SStzQWk0WS9LN1BjeHBHNlJFTk1LSnJBbjBMRXZhdlRNRkt1ZSt6d3Y5WS9iZUIKNXgvSXRybG1TcVVmYWtBb0JOWE8rN2pub2gxdDl0Q3ppMlB2U2xmSDFuczh2Y24wdmZ2NERMZXNteXpsOGo0cQpxZW1VZ0l5Y0xuaXJJakFqaUNLSXVadUlST3R6dFdCZ0dYRmdseGhpOVMvQ2Nqby9VQzZFWVNpdlE1Nlp1NGtOCnFNTmVtRWlhY0dqQ1A5VGx4NHF4OXRJM0VFajNpaDJvdUZBR0hDd3IyemxVUUY3QWJsck9tNHhQY3BJYjdnd2gKR1Uwb213ckFBNzMrdHVyUm9hZDc0THIxQWdNQkFBR2pYakJjTUE0R0ExVWREd0VCL3dRRUF3SUZvREFkQmdOVgpIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFCkZnUVVIMWNzZ3o3MnV0elVaaittWFFFQ05MOXdWdG93RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUM5SEgvM0sKMUFYQXF0SnAyZUxKTGQ4Mk45a2FUL21pZStmNDdhVjdOd2o4Q2VGZ2dsN2pNLzlvN3dTZEVuZWdRL255eHVlQQpOWHRidDQ0a0c3SklCSGR4QjlKajR5NEd6ckY2TTZLajhYUUE4dnhHSkdaNEh5WVo1QXFMS0VnTDZ6Umx0MW15CngwQm5NWWx3blMweXFsQVd5RDFjVkhjV0JoVkgxTjNDc3RnTUtzMFhrYjh3cUJBeC9wS3ZQTVlGZTEzSnhVRlEKN0xhNEkwZHNoMHNrOUo4ZEFMZTdLUmEzbzNUTGRCUFFrYmpIdVpjd1dEbEhtRDVDMDV6RDZ4QlhYbERnbEt1VgpRUlNobWJadVZFemkwbkFVVjhZYm9sWlE5QmowYkNQRzlLMUZJWE1iVE8vQnQ5cWZGTVB4cHh6Mlgxb3gvSzJFCkN6WjI2b1lDM0ViYlNwTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdXF6eTc1WVVhUWJOY1NSZlpwa0pyTGY1MGVBcEc3b29sMGoyRHB2VGNXWS9xNjRhCkE3M0dzOGtpblhqUXZYN2lUQnQrMEtVZzhlMG9qN2lQckFJdUdQeXV6M01hUnVrUkRUQ2lhd0o5Q3hMMnIwekIKU3JudnM4TC9XUDIzZ2VjZnlMYTVaa3FsSDJwQUtBVFZ6dnU0NTZJZGJmYlFzNHRqNzBwWHg5WjdQTDNKOUwzNworQXkzckpzczVmSStLcW5wbElDTW5DNTRxeUl3STRnaWlMbWJpRVRyYzdWZ1lCbHhZSmNZWXZVdnduSTZQMUF1CmhHRW9yME9lbWJ1SkRhakRYcGhJbW5Cb3dqL1U1Y2VLc2ZiU054Qkk5NG9kcUxoUUJod3NLOXM1VkVCZXdHNWEKenB1TVQzS1NHKzRNSVJsTktKc0t3QU85L3JicTBhR25lK0M2OVFJREFRQUJBb0lCQVFDcFkzNGR3UVZNT0F2NwplcEhHdTE5NEJvajkxSFg0M3ZjdUw5cDJieGR5Y3VHYm15T24rWEJ3ZXphWnhhTkVEL3F3TE5McDZLejRXY2JRCmd4eDdiSTcveFdtcWZEdC8xTVRRUHkxaUJLUUtoRzZycXU1S0xHWkJxOU9nb0xqL2V3WHdUejMwZ0E5TmJsQkIKQUFJekMxOUJjRzFiOXZaeHRTNDlXQ3hHL1d4ZU5CeHVSWkhMeFdxT0VNLy8zMzhrSVhLM1VJMVJVMDZqREl2UgpsSUFWZE9WNGtwTTRmUGgraUk3UlVSWk04VWFVandYeUM2Q2FQbEhpRGg3dmpHOFZzRkFCYzBCWFlxUkJLWDNlClZOa3hJVXJJV1doUENLZzlJRk1JaEhjY3NnQ21KVlhCSUU5S0lXMEhmY3ZsdDV6YWNhZUcwU3gyMFVHTlgzZjYKWWNBNklQU1JBb0dCQU5xZ3o4Ulc3djlQODcwREJlYVZYUEF1clkyMjdDNDVjQVZVMlJyWHVodWFlSDc2Q1RhbApYRStzY2lXOVlaa0FicVhQUkRGeCtKaTRkUG1GMS9kcHRZMEtWZUhVSCtQVEVWb1piVDlWeG9Tb2t2bDIvWVdxClh4N2ZCdEVRWTRtMENDQ0krOXA2TDY2bTZyUjkzeGFVMEJKN0lyZXJwemlLVEwwZEUyR1dtdXVIQW9HQkFOcVYKNDZUeS8xbzUyMEltSFlIeHhCcEVKWFRYQ0hmcEI1QVZGNXo1aFk2VGhHNDM3YUJ4Rms0SkVnOVRVay82ZkkxYgpIbG1tKzBtd3VYWDFXRE9QMy9pT1Jra0s4Q0IrcFVlMWoxQ1dGaTU4WDdtU1IrMFZlTGhOdmpYYld1Z2ZOQzRBCnFlVGx2K0gxanRNdlFRb0h1SUprNTVsYUNtcjZMLzBSNVBZUk5oeWpBb0dCQUxVTlVhSVdJQ3c5Q090eFVuU24KSXVVZ3NzZFdRZmJ4eUF3U1BReld0Qi9oNTRHNERPTTlROW9UUkNCdTJpRTcwMlhxNUYxU05mNDdXMXU4ZEtKRwozM3Vpb0lhNUJZUEZLbXlEL0Eza09kZG9SdmJpakljaUZVM2FncW1sdWRpeXg3d3gxT2dVSWVLd0JsUmNuTi8xCmN1NnJISkFnVGdZcnVlc3U1ZnIrSHVPSEFvR0FFbW9JS0hBMEpOUzA3T2lyR2JSVlVlVWx4cWNLMXBjeUJPaFIKK2U1bld2Q0Flb3lKbnplSHFvRkhIVFZtdk1nY1VBZzZFVkZvMy9kY1dGeVgxcGdyUlJRdlJaMy9ScTJFblBybApuT05YOFFpWFE5blg1MWdrdUZvTVNSczJtRkZ3b3VONWJJZ1NWeVhKcDI3V3F0S2xyNDV5bUUrbWl3YVNubDR3CmpLNDhnY01DZ1lFQW1WZ0s1L0RqekxOMHNlNGVlUFB6NFZuMitKRzR3TEZCU1NSVkdSdlpZbm5Ub3hYQWdtSEIKOEFpTHR5NDRLdGFReUhEeXdLNWN5T0RxbVFGN01odHhpWUE5a2t4dWpkamdCZVpRMFpMZWZQTDhQVks2d0FheApHQlVsTGZoOWR3QnpaTzcxTUV5LzdMVEUyWXpNSW9uUk5tSFdBWTh4N3F5TG1iZW1yM1VJeFl3PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=